FROM ubuntu:20.04
WORKDIR /code
RUN apt-get update && apt-get install cron -y && apt-get install python3 -y && apt-get install git -y

# Copy daily-cron file to the cron.d directory
COPY daily-git-cron /etc/cron.d/daily-git-cron
# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/daily-git-cron
# Apply cron job
RUN crontab /etc/cron.d/daily-git-cron
# Create the log file to be able to run tail
RUN touch /var/log/cron-git.log
# Run the command on container startup, 防止Exited(2)
CMD service cron start && tail -f /var/log/cron-git.log