name: "Schedule CI"
on:
  schedule:
    - cron: '30 * * * 1,3'
    - cron: '30 * * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
