name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Auto Build Docker image
      - run: |
        docker version
        if [ -e "Dockerfile" ]; then
            sh Script/build_docker_file.sh
        elif [ -e "docker-compose.yml" ]; then
            sh Script/build_docker_compose.sh
        fi
