name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Auto Build Docker image
      run: | 
        docker version
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
        first_line=$(head -n 1 Dockerfile)
        pattern="# ([^ ]+)"
        if [[ $first_line =~ $pattern ]]; then
            image_name=${BASH_REMATCH[1]}
        else
            image_name="undefine_image_name"
        fi
        docker build . --file Dockerfile --tag registry.cn-shenzhen.aliyuncs.com/$image_name/app
        docker push registry.cn-shenzhen.aliyuncs.com/$image_name/app
