name: "Tests"
on:
  pull_request:
  push:
    branches:
      - main
env:
  fail-fast: true

permissions:
  contents: read

jobs:
  test:
    name: "Testing"
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: |
            docker-compose.yml
            docker-compose.override.yml
          down-flags: "--volumes"
          services: |
            php
          env:
            TEST: 1

      - name: PHP Unit
        if: always() && steps.install.outcome == 'success'
        run: docker compose exec php bin/phpunit