name: "Docker Image CI"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: "Exec Github Action CI"
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: |
            docker-compose.yml
      - name: Auto Build Docker image
        if: always() && steps.install.outcome == 'success'
        run: |
          docker compose build
          docker image ls